import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import toast from 'react-hot-toast';
import { API, useAuth } from '../context/AuthContext';

export default function Report() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [dairies, setDairies] = useState([]);
  const [farmers, setFarmers] = useState([]); // FIX #12: farmer filter
  const [visits, setVisits] = useState([]);
  const [loading, setLoading] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);

  const defaultFrom = new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0];
  const defaultTo = new Date().toISOString().split('T')[0];
  const [filters, setFilters] = useState({ from: defaultFrom, to: defaultTo, dairy_id: '', farmer_id: '', status: '' });
  const [dateError, setDateError] = useState('');
  const setF = (k, v) => { setFilters(f => ({ ...f, [k]: v })); setDateError(''); };

  useEffect(() => {
    axios.get(`${API}/dairies`).then(r => setDairies(r.data)).catch(() => {});
    axios.get(`${API}/farmers`).then(r => setFarmers(r.data)).catch(() => {});
    fetchReport();
  }, []);

  // FIX #13: Date validation before fetching
  const validateDates = () => {
    const todayStr = new Date().toISOString().split('T')[0];
    if (filters.to && filters.to > todayStr) {
      setDateError('To date cannot be a future date');
      return false;
    }
    if (filters.from && filters.to && filters.from > filters.to) {
      setDateError('From date cannot be after To date');
      return false;
    }
    setDateError('');
    return true;
  };

  const fetchReport = async () => {
    if (!validateDates()) return;
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (filters.from) params.append('from', filters.from);
      if (filters.to) params.append('to', filters.to);
      if (filters.dairy_id) params.append('dairy_id', filters.dairy_id);
      if (filters.farmer_id) params.append('farmer_id', filters.farmer_id); // FIX #12
      if (filters.status) params.append('status', filters.status);
      const res = await axios.get(`${API}/visits?${params}`);
      setVisits(res.data);
    } catch { toast.error('Failed to load report'); }
    finally { setLoading(false); }
  };

  const downloadPDF = async () => {
    if (!validateDates()) return;
    setPdfLoading(true);
    try {
      const token = localStorage.getItem('pl_token');
      const params = new URLSearchParams();
      if (filters.from) params.append('from', filters.from);
      if (filters.to) params.append('to', filters.to);
      if (filters.dairy_id) params.append('dairy_id', filters.dairy_id);
      if (filters.farmer_id) params.append('farmer_id', filters.farmer_id);
      if (filters.status) params.append('status', filters.status);
      const res = await fetch(`${API}/reports/pdf?${params}`, { headers: { Authorization: `Bearer ${token}` } });
      if (!res.ok) throw new Error('PDF error');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `pashuledger-report-${filters.from}-to-${filters.to}.pdf`; a.click();
      URL.revokeObjectURL(url);
      toast.success('PDF downloaded!');
    } catch { toast.error('Could not generate PDF'); }
    finally { setPdfLoading(false); }
  };

  const shareWhatsApp = () => {
    const total = visits.reduce((s, v) => s + parseFloat(v.amount), 0);
    const pending = visits.filter(v => v.payment_status === 'PENDING').reduce((s, v) => s + parseFloat(v.amount), 0);
    const paid = total - pending;
    const byDairy = {};
    visits.forEach(v => {
      const key = v.dairy_name || 'Independent';
      if (!byDairy[key]) byDairy[key] = { visits: [], pending: 0 };
      byDairy[key].visits.push(v);
      if (v.payment_status === 'PENDING') byDairy[key].pending += parseFloat(v.amount);
    });
    let msg = `*PashuLedger Report*\nDr. ${user?.name || ''}\nPeriod: ${filters.from} to ${filters.to}\n\n`;
    msg += `Total Visits: ${visits.length}\nTotal Amount: ₹${total.toLocaleString('en-IN')}\nCollected: ₹${paid.toLocaleString('en-IN')}\n*Pending: ₹${pending.toLocaleString('en-IN')}*\n\n`;
    for (const [dairyName, data] of Object.entries(byDairy)) {
      if (data.pending > 0) {
        msg += `📍 *${dairyName}*\n`;
        data.visits.filter(v => v.payment_status === 'PENDING').forEach(v => {
          msg += `  - ${v.farmer_name}: ₹${parseFloat(v.amount).toLocaleString('en-IN')}\n`;
        });
      }
    }
    msg += '\n_Generated by PashuLedger | © NSN Technologies Pvt. Ltd., 2026_';
    window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, '_blank');
  };

  const total = visits.reduce((s, v) => s + parseFloat(v.amount), 0);
  const paid = visits.filter(v => v.payment_status === 'PAID').reduce((s, v) => s + parseFloat(v.amount), 0);
  const pending = total - paid;
  const fmt = n => '₹' + Number(n).toLocaleString('en-IN');
  const fmtDate = d => new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' });

  return (
    <>
      <div className="card" style={{ marginBottom: 14 }}>
        <div className="filter-row">
          <div style={{ flex: 1 }}>
            <label className="form-label">{t('fromDate')}</label>
            <input className="form-input" type="date" value={filters.from} onChange={e => setF('from', e.target.value)} />
          </div>
          <div style={{ flex: 1 }}>
            <label className="form-label">{t('toDate')}</label>
            <input className="form-input" type="date" value={filters.to} max={defaultTo} onChange={e => setF('to', e.target.value)} />
          </div>
        </div>
        {/* FIX #13: Date error message */}
        {dateError && <div className="error-msg" style={{ marginBottom: 8 }}>⚠️ {dateError}</div>}
        <div className="filter-row">
          <div style={{ flex: 1 }}>
            <label className="form-label">{t('filterDairy')}</label>
            <select className="form-input" value={filters.dairy_id} onChange={e => setF('dairy_id', e.target.value)}>
              <option value="">{t('allDairies')}</option>
              {dairies.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
            </select>
          </div>
          <div style={{ flex: 1 }}>
            <label className="form-label">{t('filterStatus')}</label>
            <select className="form-input" value={filters.status} onChange={e => setF('status', e.target.value)}>
              <option value="">{t('all')}</option>
              <option value="PENDING">{t('pending')}</option>
              <option value="PAID">{t('paid')}</option>
            </select>
          </div>
        </div>
        {/* FIX #12: Farmer filter dropdown */}
        <div className="form-group">
          <label className="form-label">{t('filterFarmer')}</label>
          <select className="form-input" value={filters.farmer_id} onChange={e => setF('farmer_id', e.target.value)}>
            <option value="">{t('allFarmers')}</option>
            {farmers.map(f => <option key={f.id} value={f.id}>{f.name}{f.village ? ` (${f.village})` : ''}</option>)}
          </select>
        </div>
        <button className="btn btn-primary" onClick={fetchReport} disabled={loading}>
          {loading ? 'Loading...' : t('generate')}
        </button>
      </div>

      {visits.length > 0 && (
        <>
          <div className="summary-row">
            <div className="summary-box"><div className="summary-box-val">{visits.length}</div><div className="summary-box-label">{t('totalVisits')}</div></div>
            <div className="summary-box"><div className="summary-box-val" style={{ color: '#185FA5' }}>{fmt(total)}</div><div className="summary-box-label">{t('totalAmount')}</div></div>
            <div className="summary-box"><div className="summary-box-val" style={{ color: '#3B6D11' }}>{fmt(paid)}</div><div className="summary-box-label">{t('collected')}</div></div>
            <div className="summary-box"><div className="summary-box-val" style={{ color: '#A32D2D' }}>{fmt(pending)}</div><div className="summary-box-label">{t('pendingAmount')}</div></div>
          </div>
          <div style={{ display: 'flex', gap: 10, marginBottom: 14, flexWrap: 'wrap' }}>
            <button className="btn btn-outline" style={{ flex: 1, minWidth: 120 }} onClick={downloadPDF} disabled={pdfLoading}>
              {pdfLoading ? '...' : `📄 ${t('downloadPDF')}`}
            </button>
            <button className="btn btn-whatsapp" style={{ flex: 1, minWidth: 120, borderRadius: 12 }} onClick={shareWhatsApp}>
              💬 {t('shareWhatsApp')}
            </button>
          </div>
          {visits.map(v => (
            <div className="visit-item" key={v.id}>
              <div className="visit-main">
                <div className="visit-name">{v.farmer_name}</div>
                <div className="visit-detail">{v.dairy_name || '—'} · {v.treatment}</div>
                <div className="visit-detail">{v.animals_count} animals · {v.village || ''}</div>
                <div style={{ marginTop: 6 }}><span className={`badge badge-${v.payment_status.toLowerCase()}`}>{v.payment_status}</span></div>
              </div>
              <div className="visit-right">
                <div className="visit-amount">{fmt(v.amount)}</div>
                <div className="visit-date">{fmtDate(v.visit_date)}</div>
                <button className="btn btn-sm"
                  style={{ marginTop: 6, background: v.payment_status === 'PENDING' ? '#EAF3DE' : '#FAEEDA', border: 'none', color: v.payment_status === 'PENDING' ? '#3B6D11' : '#854F0B' }}
                  onClick={async () => {
                    const newStatus = v.payment_status === 'PENDING' ? 'PAID' : 'PENDING';
                    await axios.patch(`${API}/visits/${v.id}/payment`, { status: newStatus });
                    setVisits(vs => vs.map(x => x.id === v.id ? { ...x, payment_status: newStatus } : x));
                  }}>
                  {v.payment_status === 'PENDING' ? t('markPaid') : t('markPending')}
                </button>
              </div>
            </div>
          ))}
        </>
      )}
      {visits.length === 0 && !loading && (
        <div className="empty-state">
          <span className="empty-icon">📊</span>
          <p className="empty-text">No visits in this period.<br />Try changing the date range.</p>
        </div>
      )}

      {/* FIX #5: Back nav */}
      <div className="nav-btns" style={{ marginTop: 8 }}>
        <button className="btn btn-outline btn-sm-nav" onClick={() => navigate('/visits/add')}>← {t('back')}</button>
      </div>
    </>
  );
}
